# Generated by Django 5.2.7 on 2025-10-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ong_app', '0002_alumno_usuario_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'Notas',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'managed': False},
        ),
    ]
